export type Zone =
  'start'
  | 'stop'
  | 'init'
  | 'error'
  | 'before.feature'
  | 'after.feature'
  | 'before.scenario'
  | 'after.scenario'
  | 'before.step'
  | 'after.step'
  | 'step'
  | 'step.pass'
  | 'step.fail'
  | 'recipe'
  | 'recipe.pass'
  | 'recipe.fail';