import { AssertStep, CheckStep, DevStep, SayStep, UIStep } from './command';

export type SupportDebug<T> = T | DevStep | SayStep;

export type Walk =
  [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>]
  | [...Array<SupportDebug<UIStep>>, CheckStep, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>, SupportDebug<AssertStep>];


