export type Zone =
  'project:start'
  | 'project:stop'
  | 'project:init'
  | 'project:error'
  | 'feature:before'
  | 'feature:after'
  | 'scenario:before'
  | 'scenario:after'
  | 'step:before'
  | 'step:after'
  | 'step'
  | 'step:pass'
  | 'step:fail'
  | 'recipe'
  | 'recipe:pass'
  | 'recipe:fail';