export type Zone =
  'platform:mount'
  | 'platform:unmount'
  | 'project:mount'
  | 'project:unmount'
  | 'project:init'
  | 'project:error'
  | 'feature:before'
  | 'feature:after'
  | 'scenario:before'
  | 'scenario:after'
  | 'step:before'
  | 'step:after'
  | 'step'
  | 'step:pass'
  | 'step:fail';